### ISSUE TITLE
The transition matrix seems is about continuous system instead of discrete one?

### ISSUE THREAD

**Issue by chenchr** [leokoppel/msckf#1]
Hello. Thanks for the code! I see here https://github.com/leokoppel/msckf/blob/master/src/msckf/EKF.cpp#L71,
about the "rot over rot".
```
F.block(COV_ROT, COV_ROT, 3, 3) = -crossMatrix(rot_vel);      // rotation wrt rotation
```
In the msckf paper it is the F of continuous system.
Can the code works?

**Comment by chutsu** [comment]
The F matrix is discretized when calculating the covariances, see this line in particular
https://github.com/leokoppel/msckf/blob/master/src/msckf/EKF.cpp#L84

Note: `F` is multiplied by `dt`

That line where `I + F dt` is from Eq. 11, in [Keyframe-Based Visual-Inertial SLAM Using
Nonlinear Optimization, by Leutenegger et al](http://www.roboticsproceedings.org/rss09/p37.pdf). Where it is a "simple Euler-Forward method
for integration over a time difference dt."

**Comment by chenchr** [comment]
@chutsu I got your point. Thank you!

**Comment by leokoppel** [comment]
Thanks @chutsu 

Here is a helpful paper describing the simpler formulation of MSCKF:
[Clement et al.,The Battle for Filter Supremacy: A Comparative Study of the Multi-State Constraint Kalman Filter and the Sliding Window Filter](http://www.starslab.ca/wp-content/papercite-data/pdf/2015_clement_battle.pdf)
